version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-cache-{{ checksum "yarn.lock" }}
            - dependencies-cache-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - ~/.cache/Cypress
          key: dependencies-cache-{{ checksum "yarn.lock" }}

      - run: yarn run test
